Review-Cock/review-cock

backend/src/main/java/com/example/backend/campaign/domain/CampaignCategory.java, backend/src/main/java/com/example/backend/campaign/domain/CampaignImage.java, backend/src/main/java/com/example/backend/campaign/domain/CampaignKeyword.java, backend/src/main/java/com/example/backend/file/domain/File.java, backend/src/main/java/com/example/backend/keyword/domain/Keyword.java
=> Feat: Campaign 연관 엔티티 비즈니스 로직 추가 [#2]

backend/src/main/java/com/example/backend/user/domain/User.java
- #4  
- User Entity 모델링 
- 혹시 부족한 부분 있으면 말씀해주세요 !!!
=> Feat: User Entity  모델링 [#4]

backend/src/main/java/com/example/backend/campaign/domain/Campaign.java, backend/src/main/java/com/example/backend/campaign/domain/CampaignAddress.java
=> Feat: Campaign 제약조건 변경 [#2]

frontend/src/components/Register/ImageUpload/index.style.ts, frontend/src/components/Register/ImageUpload/index.tsx, frontend/src/pages/Register/index.tsx
- #10 
- 이미지 미리보기, 삭제 구현
- drag & drop 구현
- 캠페인 등록 api request를 formdata 타입으로 변경
- 캠페인 타입 파일로 분리해도 될까요?
=> [FE][Feat] 캠페인 등록페이지 변경

backend/src/main/java/com/example/backend/common/security/SecurityConfig.java
=> Feat: CORS 권한 설정 SecurityConfig.java 수정

frontend/src/components/Register/Checkbox/index.tsx, frontend/src/index.tsx, frontend/src/pages/Register/index.styles.ts, frontend/src/pages/Register/index.tsx
=> [FE][Feat] 캠페인 등록페이지 유효성 검사, Request 수정

backend/.gitignore, backend/docker/README.md, backend/docker/docker-compose.yml, backend/docker/scripts/connect_mariadb.sh, backend/docker/scripts/connect_shell.sh, backend/docker/scripts/start.sh, backend/docker/scripts/stop.sh
- #31 
- Docker로 Database 컨테이너 띄우기
=> Feat: 컴포즈 파일 작성 및 쉘 스크립트 추가 [#31]

backend/src/main/java/com/example/backend/common/security/jwt/TokenProvider.java, backend/src/main/java/com/example/backend/user/controller/OAuthController.java, backend/src/main/java/com/example/backend/user/controller/UserController.java, backend/src/main/java/com/example/backend/user/domain/TokenInfo.java, backend/src/main/java/com/example/backend/user/domain/User.java, backend/src/main/java/com/example/backend/user/dto/AccessToken.java, backend/src/main/java/com/example/backend/user/repository/RefreshTokenRepository.java, backend/src/main/java/com/example/backend/user/service/KakaoOAuthService.java, backend/src/main/java/com/example/backend/user/service/NaverOAuthService.java, backend/src/main/java/com/example/backend/user/service/UserService.java
=> Refactor: user 모듈 리팩토링 [#4]

backend/src/main/java/com/example/backend/campaign/dto/DeadlineCampaign.java, backend/src/main/java/com/example/backend/campaign/dto/DetailCampaign.java, backend/src/main/java/com/example/backend/campaign/dto/PopularCampaign.java
=> Feat: campaign response file 수정 [#2]

frontend/src/pages/Detail/index.tsx
=> Feat: 캠페인 데이터 받아오기 [#15]

frontend/.gitignore, frontend/src/Layouts/CampaignItemLayout/index.styles.tsx, frontend/src/Layouts/CampaignItemLayout/index.tsx, frontend/src/Router.tsx, frontend/src/components/Common/CampaignItem/index.styles.tsx, frontend/src/components/Common/CampaignItem/index.tsx, frontend/src/components/Common/Carousel/index.tsx, frontend/src/components/Login/Oauth/Oauth.tsx, frontend/src/pages/Home/index.styles.tsx, frontend/src/pages/Home/index.tsx
- #21 
- 실제 데이터를 받아와서  핫캠페인, 마감임박 캠페인을 나타내도록 구현
=> 홈페이지 실제 데이터를 받아와 나타내는 기능 구현 

frontend/src/components/Common/NavigationBar/index.tsx, frontend/src/components/Join/JoinForm/index.tsx
=> Fix: redirect 수정

backend/src/main/java/com/example/backend/common/config/WebConfig.java
=> Feat: CORS 설정 [#2]

backend/src/main/java/com/example/backend/campaign/controller/CampaignController.java, backend/src/main/java/com/example/backend/campaign/service/CampaignService.java, backend/src/main/java/com/example/backend/common/config/SwaggerConfig.java
=> Feat: 캠페인 참가 [#2]

frontend/src/components/Login/LoginForm/index.tsx
=> Rename: login api

frontend/src/components/Login/LoginForm/index.tsx, frontend/src/pages/Detail/index.tsx, frontend/src/pages/Home/index.tsx, frontend/src/pages/Register/index.tsx
=> Refactor: axois > axiosInstanse 로 변경

frontend/src/components/Login/LoginForm/index.tsx, frontend/src/components/Logout/index.tsx, frontend/src/utils/constants/apiConstants.ts
- logout 프론트 측에서만 처리 해둔것을 백엔드에 요청하도록 수정 
- 요청 url 상수화 리팩토링
=> Refactor: logout url 수정 및 api 요청

frontend/src/components/Detail/KakaoMap/index.tsx, frontend/src/pages/Detail/index.tsx
- #52 
- 상세페이지 이동 시 이전 게시물의 지도를 출력하는 문제 수정
- 신청마감일에 캠페인 신청버튼 비활성화 되는 문제 수정
=> Fix: 상세페이지 오류 수정

frontend/src/components/Register/Checkbox/index.tsx, frontend/src/pages/Register/index.tsx, frontend/src/utils/api/register.ts, frontend/src/utils/constants/apiConstants.ts, frontend/src/utils/constants/registerConstants.ts
- #55 
- 모집인원 placeholder 보이게 수정, 카테고리 선택추가
- useMutation에서 캠페인 등록함수 분리
- 유효성 검사 상수 분리
=> Refactor: 캠페인 등록페이지

frontend/src/components/Join/JoinForm/index.tsx, frontend/src/components/Login/LoginForm/index.tsx, frontend/src/utils/constants/apiConstants.ts, frontend/src/utils/constants/joinConstants.ts, frontend/src/utils/constants/loginConstants.ts, frontend/src/utils/constants/routesConstants.ts
=> Refactor: Login 하드코딩 방지를 위해 상수로 변경

frontend/src/pages/Detail/index.tsx, frontend/src/utils/api/detail.ts, frontend/src/utils/constants/apiConstants.ts
=> Feat: 체험단 신청하기 구현

frontend/src/Router.tsx, frontend/src/components/Login/Oauth/Oauth.tsx
=> Feat: Oauth 기능 naver, kakao 기능 구현

backend/src/main/java/com/example/backend/auth/domain/Token.java, backend/src/main/java/com/example/backend/auth/support/oauth/OAuthInfoResponse.java, backend/src/main/java/com/example/backend/auth/support/oauth/OAuthLoginService.java, backend/src/main/java/com/example/backend/auth/support/oauth/RequestOAuthInfoService.java, backend/src/main/java/com/example/backend/auth/support/oauth/kakao/KakaoApiClient.java, backend/src/main/java/com/example/backend/auth/support/oauth/kakao/KakaoInfoResponse.java, backend/src/main/java/com/example/backend/auth/support/oauth/naver/NaverInfoResponse.java, backend/src/main/java/com/example/backend/campaign/domain/Campaign.java, backend/src/main/java/com/example/backend/campaign/domain/CampaignImage.java, backend/src/main/java/com/example/backend/campaign/domain/CampaignKeyword.java, backend/src/main/java/com/example/backend/file/domain/File.java, backend/src/main/java/com/example/backend/keyword/domain/Keyword.java, backend/src/main/java/com/example/backend/user/domain/User.java
=> Feat: Kakao 로그인

backend/src/main/java/com/example/backend/auth/support/oauth/OAuthInfoResponse.java, backend/src/main/java/com/example/backend/auth/support/oauth/OAuthLoginService.java, backend/src/main/java/com/example/backend/auth/support/oauth/kakao/KakaoApiClient.java, backend/src/main/java/com/example/backend/auth/support/oauth/kakao/KakaoInfoResponse.java, backend/src/main/java/com/example/backend/auth/support/oauth/naver/NaverInfoResponse.java, backend/src/main/java/com/example/backend/campaign/controller/CampaignController.java, backend/src/main/java/com/example/backend/campaign/domain/Campaign.java, backend/src/main/java/com/example/backend/campaign/domain/Participant.java, backend/src/main/java/com/example/backend/campaign/service/CampaignService.java
=> Fix: kakao login 수정

backend/src/main/java/com/example/backend/common/exception/campaign/CampaignNotParticipateException.java
=> Feat: 캠페인 참가 validation

frontend/src/App.tsx
- 새로고침시  Refresh-Token을 통해 Access-Token 재발급 기능 구현
=> Feat: 새로고침시  Refresh-Token을 통해 Access-Token 재발급 기능
